const ESCAPE_BUTTON_KEY = 'Escape';
const FORM_WHITE_THEME = 'white';
const FORM_DARK_THEME = 'dark';
const AUTH_STORAGE_TOKEN_KEY = 'auth';

export {
  ESCAPE_BUTTON_KEY,
  FORM_WHITE_THEME,
  FORM_DARK_THEME,
  AUTH_STORAGE_TOKEN_KEY,
};
